Update HTTP Cache Partitioning article
google/WebFundamentals pull request #9075
Opened 2020-10-20 06:12 UTC by agektmr

What's changed, or what was fixed?
- Updates HTTP Cache Partitioning article

**Target Live Date:** 2020-10-24

- [ ] This has been reviewed and approved by (NAME)
- [x] I have run `npm test` locally and all tests pass.
- [x] I have added the appropriate `type-something` label.
- [x] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele @shivanigithub

2020-10-21 15:08 UTC, agektmr commented
@kaycebasques @jpmedley May I ask one of you to review this pull request? Thanks.

2020-10-21 15:20 UTC, shivanigithub commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +followed by `Control_[****]` or `Default_[****]`, not enabled.
nit: "not enabled" to be replaced with "it is not enabled"

2020-10-21 15:22 UTC, shivanigithub reviewed
The changes lgtm, thanks!

2020-10-21 17:37 UTC, jpmedley requested changes

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +already in effect, follow the instructions below:
```suggestion
The feature is being rolled out through late 2020. To check whether your Chrome instance
already supports it:
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +7. You will see the output of the log file.
```suggestion
6. Press **Choose File** and pass the log file you saved. 

You will see the output of the log file.
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +7. You will see the output of the log file.
The best practice is that steps only begin with a user action. Responses to steps are tacked at the end of the step. The result of the whole procedure is in a separate paragraph at the end.

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +followed by `Control_[****]` or `Default_[****]`, not enabled.
```suggestion
followed by `Control_[****]` or `Default_[****]`, it is not enabled.
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +`Experiment_[****]`, HTTP Cache Partitioning is enabled on your Chrome. If it is
```suggestion
`Experiment_[****]`, HTTP Cache partitioning is enabled on your Chrome. If it is
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +### How can I test HTTP Cache Partitioning on my Chrome?
```suggestion
### How can I test HTTP Cache partitioning on my Chrome?
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +To test HTTP Cache Partitioning on your Chrome, you need to launch Chrome with a
```suggestion
To test HTTP Cache partitioning on your Chrome, you need to launch Chrome with a
```

2020-10-21 17:37 UTC, jpmedley commented on src/content/en/updates/2020/10/http-cache-partitioning.md
> +command line flag `--enable-features=SplitCacheByNetworkIsolationKey`. Follow
```suggestion
command line flag: `--enable-features=SplitCacheByNetworkIsolationKey`. Follow
```

2020-10-22 06:02 UTC, agektmr commented
Thanks for the reviews. I'll merge.

2020-10-22 06:02 UTC, merged