Fixes #9241 - Remove references to Accept-CH-Lifetime
google/WebFundamentals pull request #9242
Opened 2021-02-03 18:07 UTC by miketaylr

It's been removed from relevant specs, and we shouldn't encourage its use.

What's changed, or what was fixed?
- I removed references to `Accept-CH-Lifetime`.

**Fixes:** #9241

**Target Live Date:** YYYY-MM-DD

- [ ] This has been reviewed and approved by (NAME)
- [ ] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele
@yoavweiss @rowan-m

2021-02-11 15:52 UTC, petele commented
@philipwalton - can you take a look and approve if appropriate?

2021-02-15 11:57 UTC, rowan-m requested changes
Straightforward removal, but added a little section to call out the removal rather than it just disappearing from the article in case people have been depending on it. @miketaylr I'm happy with the rest, so could you just verify my bit.

2021-02-16 19:35 UTC, miketaylr commented
> @miketaylr I'm happy with the rest, so could you just verify my bit.

@rowan-m yep, looks good - thanks! (feel free to merge)

2021-02-17 16:04 UTC, rowan-m approved these changes
LGTM

2021-02-17 18:35 UTC, merged